### ISSUE TITLE
blogify(".") produces blank html file

### ISSUE THREAD

**Issue by jvcasillas** [ramnathv/poirot#31]
I'm trying to integrate poirot with by website and I'm pretty sure I haven't set up the config.yml or the site.yml files correctly. When I use the blogify() command both of the appropriate .md and .html files are produced; however, the .html file is blank. The .md file looks fine. The R code is run and the correct output is there, but there is nothing in the .html file. Has anybody had this problem before? There is no error output in the console. It says:

```
output file: 2014-05-24-test_post.md

Blogification Successful :-)
```

**Comment by ramnathv** [comment]
You should run `blogify(".")` from the root directory of the blog. The `posts` directory will be a subdirectory of the blog and is currently hardcoded in `poirot`. Let me know if that works.

**Comment by jvcasillas** [comment]
Hi. I tried this and I am getting the same result. The markdown file is produced and has the r code with the desired outcome, but the .html file is still empty.

**Comment by ghost** [comment]
Were you able to reproduce the example blog?

**Comment by jvcasillas** [comment]
Yes. In fact, I was able to generate new posts in the example blog with no problems. I think the problem has to do with the .yml files being setup incorrectly. I was hoping that a blank html file might be a clue as to what went wrong.

**Comment by ramnathv** [comment]
Can you post your `.yml` files so that I can take a look? Did you install the `slidifyLibraries` package?

**Comment by jvcasillas** [comment]
config.yml in root

```
title: title
name: name
email: myemail
github: jvcasill
twitter: jvcasill
pygments: true
timezone: TIMEZONE
markdown: kramdown

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify

# Settings for analytics
analytics :
  provider : google
  google : 
      tracking_id : ############
```

site.yml

```
title: title
tagline: testing
owner: me
author:
  email: myemail
  github: jvcasill
  firstname: name
  lastname: name

social:
  github: username
  twitter: username

# Choose url: / for local development
url: http://jvcasill.github.com/jvcasill/
rawurl: https://raw.github.com/jvcasill/jvcasill/gh-pages/
# url: /
URL: http://github.com/jvcasill/jvcasill
navigation: 
  - {item: Home, href: index.html}
```

config.yml in posts

```
mode     : selfcontained
framework: purus
github:
  user: jvcasill
  repo: jvcasill

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

url:
  lib: ../libraries
  assets: ../assets

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify
```
